#!/usr/bin/python

from optparse import OptionParser
import os
import threading
import sys

from lib import CMDUtils
from lib import ADBUtils


# ------------------------------------------- ARG PARSE -----------------------------------------------------#

CMDUtils.clear()

parser = OptionParser()
parser.add_option("-f", "--file", type="string", dest="file", default="", help="Path-To-APK")
parser.add_option("-u", "--uninstall", action="store_true", dest="uninstall", default=False, help="Uninstalls the apk")
parser.add_option("-i", "--install", action="store_true", dest="install", default=False, help="Installs the apk")
parser.add_option("-l", "--launch", action="store_true", dest="launch", default=False, help="Launch the apk")
(arguments, args) = parser.parse_args()

# ------------------------------------------- ARG VALIDATIONS -----------------------------------------------------#

if len(sys.argv) == 1:
    parser.print_help()
    exit(1)

if not os.path.isfile(arguments.file):
    CMDUtils.print_error("File does not exists: " + arguments.file)

devices = ADBUtils.get_connected_devices()

if len(devices) == 0:
    CMDUtils.print_error("No devices connected")


# ------------------------------------------------------------------------------------------------------#
# ------------------------------------------- MAIN -----------------------------------------------------#
# ------------------------------------------------------------------------------------------------------#


# List devices
ADBUtils.pretty_print_devices()


# Start
package = ADBUtils.get_package_from_apk(arguments.file)
main_activity = package + "/" + ADBUtils.get_launchable_activity(arguments.file)


if (arguments.install != False):

	#INSTALL APP

	#DEVIDE ID AND APK FILE    REQUIRED

	for device in devices:
		threading.Thread(target=ADBUtils.install, args=(device, arguments.file)).start()

else: 

	package = ADBUtils.get_package_from_apk(arguments.file)

	if(arguments.launch != False):

		#RUNS APP

		#DEVIDE ID AND ACTIVITY FULL PATH    REQUIRED

		activity_full_path = package + "/" + ADBUtils.get_launchable_activity(arguments.file)
		for device in devices:
			threading.Thread(target=ADBUtils.run, args=(device, activity_full_path)).start()

	else:
		if(arguments.uninstall != False):

			#UNISTALL APP

			#DEVICE ID AND PACKAGE REQUIRED

			for device in devices:
				threading.Thread(target=ADBUtils.uninstall, args=(device, package)).start()
